[book]
authors = ["Rodygin Pavel"]
language = "en"
multilingual = false
src = "src"
title = "M3137 c++"


[build]
build-dir = "book"

[output.html]
default-theme = "ayu"
mathjax-support = true
#curly-quotes = false  # Отключает преобразование прямых кавычек в "умные" кавычки
git-repository-url = "https://github.com/pasharodygin/cpp_tickets"



